version: '3.7'
services:
  app:
    image: node:8.14.0-alpine
    ports:
      - "1234:1234"
    working_dir: /opt/reactodo/
    volumes:
      - ./:/opt/reactodo/
    entrypoint: npm
    command: start
